### ISSUE TITLE
Missing instructions in official website

### ISSUE THREAD

**Issue by machadolucasvp** [dracula/prism#10]
Current [link](https://draculatheme.com/prism/) in readme is broken

**Comment by gusbemacbe** [comment]
Hello/Olá @lucasvufma !

Prism is not listed in the official Dracula site. 
Prism não está incluído no site oficial de Dracula.

I must call @zenorocha to analyse this issue. 
Devo chamar @zenorocha para analisar este problema.

**Comment by zenorocha** [comment]
Hey @gusbemacbe, that's because the repository is not following the same pattern needed for the site.

Can you please follow the [template](https://github.com/dracula/template) and make these changes?

1. Create a INSTALL.md and move the instructions there
2. Use a similar README.md to the template
3. Move and rename `images/previsao.png` to `screenshot.png`

Thanks!

**Comment by gusbemacbe** [comment]
@zenorocha 

Sorry for my absence, I was working a lot, reorganising my lost files and the folders. But I have just updated, following the Dracula template. It is ready. See if it is all good.

**Comment by zenorocha** [comment]
Aaaand we're live! 🎉 🎉 🎉 

https://draculatheme.com/prism

Thanks @machadolucasvp for reporting and @gusbemacbe for working on this ;D
